export interface IInscripcion {
  id: number
  access_token: string
  alumnoapellido: string
  alumnocuil: string
  alumnoestadocivil: string
  alumnogenero: string
  alumnogenerodet: string
  alumnonombres: string
  alumnonumerodocumento: string
  alumnosexo: string
  alumnotipodocumento: string
  anioingreso: number
  carrera_preseteada: number
  casacondicion: string
  casamediotraslado: string
  casatipo: string
  contactoemail: string
  contactoemailalternativo: string
  contactotelefonofijo: string
  contactotelefonomovil: string
  deporte: string
  documentacionanalitico: string
  documentacioncertmaterias: string
  documentacioncuil: string
  documentacioncv: string
  documentaciondni: string
  documentaciondniback: string
  documentacionnacimiento: string
  documentaciontitulogrado: string
  domiciliocalle: string
  domiciliocp: string
  domiciliolocalidad: string
  domicilionumero: string
  domiciliopartido: string
  domiciliopiso: string
  domicilioprovincia: string
  emergenciacontacto: string
  emergenciatelefono: string
  error_sysacad: Text
  familiaacargo: string
  fecha_cierre: Date
  fecha_inicio: Date
  fecha_sysacad: Date
  formaingreso: string
  hermanosactividades: string
  hermanoscantidad: string
  hermanosedades: string
  hijosacargo: string
  id_carrera: number
  introductoriointensivo: string
  legajo_sysacad: string
  lugarcursado: string
  madreapellido: string
  madreestudios: string
  madrefechanac: string
  madrenombre: string
  madreobrasocial: string
  madresituacionlaboral: string
  madretrabajo: string
  madrevive: string
  nacfechanacimiento: string
  nacgruposanguineo: string
  naclocalidad: string
  nacnacionalidad: string
  nacpais: string
  nacpartidodepartamento: string
  nacprovincia: string
  nacvencdni: string
  nroTramiteDni: string
  otrosestudioscarrera: string
  otrosestudiosestado: string
  otrosestudiosinstitucion: string
  otrosestudiosmateriasaprobadas: string
  otrosestudiostipo: string
  padreapellido: string
  padreestudios: string
  padrefechanac: string
  padrenombre: string
  padreobrasocial: string
  padresituacionlaboral: string
  padretrabajo: string
  padrevive: string
  secundarioanalitico: string
  secundarioanioegreso: string
  secundariocue: string
  secundariodependede: string
  secundarioegreso: string
  secundarioestado: string
  secundarioinstitucion: string
  secundariolocalidad: string
  secundarioprovincia: string
  secundariotecnico: string
  secundariotituladoen: string
  situacionlaboral: string
  state: string
  state_messages: string
  tecnocelular: string
  tecnodondepc: string
  tecnointernet: string
  tecnotieneinternet: string
  tecnotienepc: string
  tecnousointernet: string
  tipocursado: string
  tipoocupacion: string
  tipotrabajo: string
  titulounivanioegreso: string
  titulounivcue: string
  titulouniventramite: string
  titulounivinstitucion: string
  titulounivlocalidad: string
  titulounivnombre: string
  titulounivprovincia: string
  trabajodireccion: string
  trabajoempresa: string
  trabajoenque: string
  trabajohoras: string
  trabajoocupacion: string
  trabajorelcarrera: string
  trabajotelefono: string
  trabajotrabajas: string

}